In [18]:

%load_ext autoreload
%autoreload 2
import concurrent.futures
import numpy as np
from georges_core.codes_io.bdsim import *


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [29]:

output = BDSimOutput("/Users/chernals/Downloads/new_simu_82_5.root")


In [8]:
output.event.tree['Histos.'].keys()


[b'Histos.TObject',
 b'Histos.histograms1D',
 b'Histos.histograms2D',
 b'Histos.histograms3D']

In [30]:
# %%timeit -n 1 -r 1
executor = concurrent.futures.ThreadPoolExecutor(max_workers=8)
output = BDSimOutput("test-1.root", path='/Users/chernals/cernbox')
ar = output.event.tree.arrays(branches=output.event.tree['Histos.'].keys()[1:4:2],
                              executor=executor)
r = {}
for k, v in ar.items():
    for i in range(0, len(v)):
        r[f"{k}_{i}"] = merge_histograms(v, i)
r
#ar3d = output.event.tree['Histos.histograms3D'].array()


IndexError: list index out of range

In [25]:
ar

{b'Histos.histograms1D': <ObjectArray [[<b'TH1D' b'PhitsHisto' 0x7fa24b9ccd18>, <b'TH1D' b'PlossHisto' 0x7fa24b9ccb38>, <b'TH1D' b'ElossHisto' 0x7fa24b9cc098>, <b'TH1D' b'PhitsPEHisto' 0x7fa24b9cc6d8>, <b'TH1D' b'PlossPEHisto' 0x7fa24b9cc8b8>, <b'TH1D' b'ElossPEHisto' 0x7fa24bcadd18>] [<b'TH1D' b'PhitsHisto' 0x7fa24b9cc7c8>, <b'TH1D' b'PlossHisto' 0x7fa24bcad958>, <b'TH1D' b'ElossHisto' 0x7fa24bcad4a8>, <b'TH1D' b'PhitsPEHisto' 0x7fa24bcad2c8>, <b'TH1D' b'PlossPEHisto' 0x7fa24bcadc28>, <b'TH1D' b'ElossPEHisto' 0x7fa24bca2958>] [<b'TH1D' b'PhitsHisto' 0x7fa24b9cc0e8>, <b'TH1D' b'PlossHisto' 0x7fa24b9ccb38>, <b'TH1D' b'ElossHisto' 0x7fa24b9cc098>, <b'TH1D' b'PhitsPEHisto' 0x7fa24b9cc6d8>, <b'TH1D' b'PlossPEHisto' 0x7fa24bcadd68>, <b'TH1D' b'ElossPEHisto' 0x7fa24bcad408>] ... [<b'TH1D' b'PhitsHisto' 0x7fa24b9cc228>, <b'TH1D' b'PlossHisto' 0x7fa24b9ccb38>, <b'TH1D' b'ElossHisto' 0x7fa24b9cc098>, <b'TH1D' b'PhitsPEHisto' 0x7fa24b9cc6d8>, <b'TH1D' b'PlossPEHisto' 0x7fa24b9ccef8>, <b'TH1D' b'

In [29]:

def discover_histograms(histograms):
    return {h.name.decode('utf-8'): i for i, h in enumerate(histograms[0])}

def merge_histograms(histograms, index):
    _ = np.array([
        h[index].values for h in histograms
    ])
    return np.mean(_, 1), np.std(_, 1)


In [86]:

%%timeit -n 1 -r 1
output = BDSimOutput("test-1.root", path='/Users/chernals/cernbox')
ar1d = output.event.tree['Histos.histograms1D'].array()
print(merge_histograms(ar1d, 0))



0.0012484394506866417
21.8 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [63]:

%%timeit -n 1 -r 1
tmp.shape


1.98 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [31]:

output.header.header.df


bdsimVersion                      geant4Version  \
entry                                                                       
0      b'v1.3.2-1849-gde1916b91-dirty'  b'$Name: geant4-10-05-patch-01 $'   

       ootVersion clhepVersion                      timeStamp  fileType  \
entry                                                                     
0      b'6.18/04'   b'2.4.1.2'  b'Mon Mar 16 10:55:20 2020\n'  b'BDSIM'   

       taVersion  oublePrecisionOutput nalysedFiles combinedFiles  \
entry                                                               
0              5                 False           []            []   

       nTrajectoryFilters                                  trajectoryFilters  
entry                                                                         
0                       9  [b'primary', b'depth', b'particle', b'energyTh...

In [63]:

o = ReBDSimOpticsOutput("/Users/chernals/Downloads/optics_alpha_0.1.root")
o.optics.df.values


Trying to return optics.optics


array([[ 9.99582538e-51,  9.98287483e-51, -2.50781380e-04,
         3.19348647e-03,  1.00728621e+00,  9.94357262e-01,
         9.92766553e-01,  1.00568502e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.18697290e-28,  6.10360053e-28, -4.54273625e-28,
        -3.23430730e-28,  1.00342698e-25,  9.96320434e-26,
         9.96168716e-26,  1.00197942e-25,  0.00000000e+00,
         2.00000000e+04,  6.99733430e-53,  7.04521204e-53,
         7.06857021e-03,  7.02776422e-03,  7.05396560e-03,
         7.06125456e-03,  0.00000000e+00,  0.00000000e+00,
                    nan,             nan,             nan,
                    nan,  7.09530024e-28,  7.04504935e-28,
         7.04397654e-28,  7.08506444e-28,  4.96987490e-28,
         5.01115711e-28,  4.92990015e-28,  4.99190190e-28,
         1.16612303e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
                    nan,             nan,  5.51635125e-0

In [24]:

o.directory['Optics']['Mean_E'].name


b'Mean_E'

In [79]:

o.Eventtt


In [20]:

re = ReBDSimOutput("/Users/chernals/cernbox/scoring.root")
re.event['MergedHistograms'][b'PhitsHisto;1'].allnumpy() -


(array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 

In [19]:

re.event.MergedHistograms.PhitsHisto.allnumpy()


(array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 

In [31]:

re.event.MergedHistograms.PhitsHisto.values


array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.